---
title: "Untitled"
author: "Iris Zhong"
date: "3/6/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(readxl)
# library(readxlsb)
library(tidyverse)
```

```{r import data, report = F, output = F}
data_2020 <- read_excel(here("data/xlsx", "2020-21 Professional Personnel Individual Staff Report updated.xlsx")) %>% 
  mutate(PublicID = as.numeric(PublicID)) %>% 
  rename(YearsInEd = YearsInED) %>%
  mutate(AnnualSalary = ifelse(AnnualSalary == "Salary Excluded for Fictitious", NA, AnnualSalary))

data_2014 <- read_excel(here("data/xlsx", "2014-15 Professional Personnel Individual Staff Report.xlsx"))

data_2015 <- read_excel(here("data/xlsx", "2015-16 Professional Personnel Individual Staff Report.xlsx"))

data_2016 <- read_excel(here("data/xlsx", "2016-17 Professional Personnel Individual Staff Report.xlsx"))

data_2017 <- read_excel(here("data/xlsx", "2017-18 Professional Personnel Individual Staff Report.xlsx"))

data_2018 <- read_excel(here("data/xlsx", "2018-19 Professional Personnel Individual Staff Report.xlsx")) %>% rename(YearsInEd = YearsInED)

data_2019 <- read_excel(here("data/xlsx", "2019-20 Professional Personnel Individual Staff Report.xlsx")) %>% rename(YearsInEd = YearsInED)

```


# Clean 2014-2020 data

```{r calculate FTE for each id}
calculate_FTE <- function(data) {
  data <- data %>%
    group_by(SY, PublicID) %>%
    summarize(fte = sum(as.numeric(`FTE%`)/100))
  return(data)
}
```

```{r select data}
data_list <- list(data_2014, data_2015, data_2016, data_2017, data_2018, data_2019, data_2020)

# Remove bad rows: 
data_list <- map(data_list, function(x){x<-x %>% filter(!SchNum %in% c("9999", "Off-Site")) %>% filter(!PublicID %in% c(1880041809, -1629249266))})

temp <- lapply(data_list, calculate_FTE)

names(temp) <- c("data_2014_short", "data_2015_short", "data_2016_short", "data_2017_short", "data_2018_short","data_2019_short", "data_2020_short")

list2env(temp, envir = .GlobalEnv)
```

Join datasets


```{r join datasets}
data_14_20_short <- data_2014_short %>%
  full_join(data_2015_short, by = "PublicID") %>%
  full_join(data_2016_short, by = "PublicID") %>%
  full_join(data_2017_short, by = "PublicID") %>%
  full_join(data_2018_short, by = "PublicID") %>%
  full_join(data_2019_short, by = "PublicID") %>%
  full_join(data_2020_short, by = "PublicID")
```


```{r change column names}
data_14_20_short %>% head()

data_14_20_short <- data_14_20_short %>%
  mutate(fte_14 = fte.x, fte_15 = fte.y, fte_16 = fte.x.x,
         fte_17 = fte.y.y, fte_18 = fte.x.x.x, fte_19 = fte.y.y.y, fte_20 = fte) %>%
  select(PublicID, fte_14:fte_20)
```

```{r add zero}
data_14_20_short <- data_14_20_short %>%
  mutate(fte_14 = ifelse(is.na(fte_14) == T, 0, fte_14),
         fte_15 = ifelse(is.na(fte_15) == T, 0, fte_15),
         fte_16 = ifelse(is.na(fte_16) == T, 0, fte_16),
         fte_17 = ifelse(is.na(fte_17) == T, 0, fte_17),
         fte_18 = ifelse(is.na(fte_18) == T, 0, fte_18),
         fte_19 = ifelse(is.na(fte_19) == T, 0, fte_19),
         fte_20 = ifelse(is.na(fte_20) == T, 0, fte_20))

```

```{r reduce fte to max=1}
data_14_20_short <- data_14_20_short %>%
  mutate(fte_14 = ifelse(fte_14 > 1, 1, fte_14),
         fte_15 = ifelse(fte_15 > 1, 1, fte_15),
         fte_16 = ifelse(fte_16 > 1, 1, fte_16),
         fte_17 = ifelse(fte_17 > 1, 1, fte_17),
         fte_18 = ifelse(fte_18 > 1, 1, fte_18),
         fte_19 = ifelse(fte_19 > 1, 1, fte_19),
         fte_20 = ifelse(fte_20 > 1, 1, fte_20))  
```



```{r number of teachers each year}
sum(data_14_20_short$fte_14)
sum(data_14_20_short$fte_15)
sum(data_14_20_short$fte_16)
sum(data_14_20_short$fte_17)
sum(data_14_20_short$fte_18)
sum(data_14_20_short$fte_19)
sum(data_14_20_short$fte_20)
```

# Calculate exit rate for each year

Steps: join with previous year, set missing value = 0, find diff in FTE

Two ways:

1. only negative differences are counted (drop rate)
2. everything is counted (change rate)

```{r calculate exit rate by experience}
change_rate <- c(NA)
change_rate_year_exp <- data.frame()
# iterate over year
for (i in 3:8) {
  data_14_20_find_dropout <- data_14_20_short %>%
    mutate(fte_diff = .[[i]]-.[[i-1]])
#  data_14_20_find_dropout <- data_14_20_short
#  data_14_20_find_dropout$fte_diff <- data_14_20_find_dropout[i]-data_14_20_find_dropout[i-1]
  # dataset_name <- paste("data", i+2011, sep = "_")
  temp_data <- data_14_20_find_dropout %>%
    inner_join(data_list[[i-2]], by = "PublicID")
  temp_data <- distinct(temp_data, PublicID, .keep_all = T)
  change_rate <- append(change_rate, sum(temp_data$fte_diff)/sum(temp_data[i-1]))
  temp_data <- temp_data %>%
    group_by(YearsInEd) %>%
    summarize(n = n(),
              change_rate_by_exp = mean(change_rate, na.rm =T)) %>%
    mutate(year = paste(i+2012, i+2013-2000, sep = "-"))

   change_rate_year_exp <- rbind(change_rate_year_exp, temp_data)
}
```



```{r}
data_14_20_find_dropout <- data_14_20_short %>%
    mutate(fte_diff = fte_15 - fte_14)
```

```{r}
temp_data <- data_14_20_find_dropout %>%
    inner_join(data_2014, by = "PublicID")
temp_data <- distinct(temp_data, PublicID, .keep_all = T)
```

```{r}
temp_data %>%
  filter(fte_diff > 0)
```


