---
title: "Data Wrangling"
author: "Iris Zhong"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(readxl)
# library(readxlsb)
library(tidyverse)
```

```{r import data}
data_2020 <- read_excel(here("data/xlsx", "2020-21 Professional Personnel Individual Staff Report updated.xlsx")) %>% 
  mutate(PublicID = as.numeric(PublicID)) %>% 
  rename(YearsInEd = YearsInED) %>%
  mutate(AnnualSalary = ifelse(AnnualSalary == "Salary Excluded for Fictitious", NA, AnnualSalary))

data_2014 <- read_excel(here("data/xlsx", "2014-15 Professional Personnel Individual Staff Report.xlsx"))

data_2015 <- read_excel(here("data/xlsx", "2015-16 Professional Personnel Individual Staff Report.xlsx"))

data_2016 <- read_excel(here("data/xlsx", "2016-17 Professional Personnel Individual Staff Report.xlsx"))

data_2017 <- read_excel(here("data/xlsx", "2017-18 Professional Personnel Individual Staff Report.xlsx"))

data_2018 <- read_excel(here("data/xlsx", "2018-19 Professional Personnel Individual Staff Report.xlsx")) %>% rename(YearsInEd = YearsInED)

data_2019 <- read_excel(here("data/xlsx", "2019-20 Professional Personnel Individual Staff Report.xlsx")) %>% rename(YearsInEd = YearsInED)

```

# Exploration (don't run)



```{r use name as ID, include = F}
data_2014_clean <- data_2014 %>%
  unite("name", c(`First Name`, `MiddleName`, `Last Name`, Suffix), sep=" ", 
        remove = FALSE, na.rm = TRUE) %>%
  mutate(name = tolower(name)) %>%
  mutate(person_ID = group_indices(., name))
```



Doesn't work well 

```{r include = F}
data_2014_clean %>%
  group_by(person_ID, PublicID) %>%
  summarize(n = n()) %>%
  filter(n != 1)
```



```{r include= F}
data_2014_clean %>%
  group_by(person_ID) %>%
  summarize(n = n()) %>%
  filter(n != 1)
```


```{r include = F}
data_2014_clean %>%
  filter(person_ID ==875)
```

Only 2020-21 uses different PublicID. 


```{r include = F}
data_2014 %>%
  inner_join(data_2015, by = c("PublicID")) %>%
  filter(Status.y != "Active")
```

# Clean 2014-2020 data

Select year and public ID

```{r select func, include = F}
select_var <- function(data) {
  
  data <- data %>%
    dplyr::select(SY, PublicID)
  
}
```


```{r apply select func}
data_list <- list(data_2014, data_2015, data_2016, data_2017, data_2018, data_2019, data_2020)

temp <- lapply(data_list, function(x){x <- x %>% dplyr::select(SY, PublicID); return (x)})

names(temp) <- c("data_2014_short", "data_2015_short", "data_2016_short", "data_2017_short", "data_2018_short","data_2019_short", "data_2020_short")

list2env(temp, envir = .GlobalEnv)
```

```{r only keep distinct IDs}
data_2014_short <- distinct(data_2014_short, .keep_all = T)
data_2015_short <- distinct(data_2015_short, .keep_all = T)
data_2016_short <- distinct(data_2016_short, .keep_all = T)
data_2017_short <- distinct(data_2017_short, .keep_all = T)
data_2018_short <- distinct(data_2018_short, .keep_all = T)
data_2019_short <- distinct(data_2019_short, .keep_all = T)
data_2020_short <- distinct(data_2020_short, .keep_all = T)
```

Take a look at ID: 180041809 (a lot of rows)


```{r join datasets}
data_14_20_short <- data_2014_short %>%
  full_join(data_2015_short, by = "PublicID") %>%
  full_join(data_2016_short, by = "PublicID") %>%
  full_join(data_2017_short, by = "PublicID") %>%
  full_join(data_2018_short, by = "PublicID") %>%
  full_join(data_2019_short, by = "PublicID") %>%
  full_join(data_2020_short, by = "PublicID")
```


```{r change column names}
data_14_20_short %>% head()

data_14_20_short <- data_14_20_short %>%
  mutate(Y14 = SY.x, Y15 = SY.y, Y16 = SY.x.x,
         Y17 = SY.y.y, Y18 = SY.x.x.x, Y19 = SY.y.y.y, Y20 = SY) %>%
  select(PublicID, Y14:Y20)
```


```{r convert to binary}
data_14_20_short <- data_14_20_short %>%
  mutate(Y14 = ifelse(is.na(Y14) == T, 0, 1),
         Y15 = ifelse(is.na(Y15) == T, 0, 1),
         Y16 = ifelse(is.na(Y16) == T, 0, 1),
         Y17 = ifelse(is.na(Y17) == T, 0, 1),
         Y18 = ifelse(is.na(Y18) == T, 0, 1),
         Y19 = ifelse(is.na(Y19) == T, 0, 1),
         Y20 = ifelse(is.na(Y20) == T, 0, 1))
```



```{r number of teachers each year}
sum(data_14_20_short$Y14)
sum(data_14_20_short$Y15)
sum(data_14_20_short$Y16)
sum(data_14_20_short$Y17)
sum(data_14_20_short$Y18)
sum(data_14_20_short$Y19)
sum(data_14_20_short$Y20)
```


# Years of experience + drop out

```{r create a easier to see version}
data_14_20_short <- data_14_20_short %>%
  mutate(state = paste(Y14, Y15, Y16, Y17, Y18, Y19, Y20, sep = ""))

data_14_20_short %>%
  group_by(state) %>%
  summarize(n = n())
```

  
```{r calculate exit rate bye experience}
exit_rate <- c(NA)
exit_rate_year_exp <- data.frame()
# iterate over year
for (i in 3:8) {
  data_14_20_find_dropout <- data_14_20_short %>%
    mutate(drop_yes = ifelse(.[[i]] == 0 & .[[i-1]] == 1, 1, 0))
  # dataset_name <- paste("data", i+2011, sep = "_")
  temp_data <- data_14_20_find_dropout %>%
    inner_join(data_list[[i-2]], by = "PublicID")
  temp_data <- distinct(temp_data, PublicID, .keep_all = T)
  exit_rate <- append(exit_rate, sum(temp_data$drop_yes)/nrow(temp_data))
  temp_data <- temp_data %>%
    group_by(YearsInEd) %>%
    summarize(n = n(),
              exit_rate_by_exp = mean(drop_yes),
              exit_n_by_exp = sum(drop_yes)) %>%
    mutate(year = paste(i+2012, i+2013-2000, sep = "-"))

   exit_rate_year_exp <- rbind(exit_rate_year_exp, temp_data)
}
```
  
```{r create summary table}
year_list <- c("2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21")
n_list <- c(sum(data_14_20_short$Y14), sum(data_14_20_short$Y15), sum(data_14_20_short$Y16), sum(data_14_20_short$Y17),
            sum(data_14_20_short$Y18), sum(data_14_20_short$Y19), sum(data_14_20_short$Y20))
summary_table <- data.frame(year_list, n_list, exit_rate)
```

```{r write table}
write.csv(summary_table, "year_summary.csv", row.names = FALSE)
write.csv(exit_rate_year_exp,"exit_rate_year_exp.csv", row.names = FALSE)
```


# Draw graphs

```{r}
exit_rate_year_exp <- exit_rate_year_exp %>%
  mutate(YearsInEd = as.numeric(YearsInEd))
ggplot(exit_rate_year_exp, aes(x = YearsInEd, y = exit_n_by_exp, color = year)) +
  geom_point() +
  geom_line()
```

```{r}
ggplot(exit_rate_year_exp, aes(x = YearsInEd, y = exit_rate_by_exp, color = year)) +
  geom_point() +
  geom_line()
```



# Number of teachers per school

```{r}
teacher_n_by_school <- data.frame()
for (i in 1:7) {
  temp_data <- distinct(data_list[[i]], PublicID, .keep_all = T)
  temp_data <- temp_data %>%
    group_by(SchNum) %>%
    summarize(teacher_n = n()) %>%
    mutate(year = i+2013)
  teacher_n_by_school <- rbind(teacher_n_by_school, temp_data)
  
}
```

```{r include = F}
teacher_n_by_school <- teacher_n_by_school %>%
  pivot_wider(id_cols = "SchNum", names_from = "year", values_from = "teacher_n")
```

0000, 9999, Off-Site has too many teachers: remove

```{r}
teacher_n_by_school <- teacher_n_by_school %>% filter(!SchNum %in% c("0000", "9999", "Off-Site"))
```

```{r}
teacher_n_by_school %>% filter(teacher_n > 500)
```

```{r}
teacher_n_summary <- teacher_n_by_school %>%
  group_by(year) %>%
  summarize(mean_n = mean(teacher_n, na.rm = T),
            school_n = n(), 
            se_n = sd(teacher_n)/sqrt(school_n),
            ci = se_n*1.96)

teacher_n_summary
```



```{r}
ggplot(data = teacher_n_by_school, 
       aes(x = year, y = teacher_n)) + 
  geom_line(aes(group = SchNum), 
            alpha = .05, width = .25) + 

  ylim(0,150) 
```

```{r}
plot_n <- ggplot(teacher_n_summary, aes(x = year, y = mean_n)) +
  geom_line(color = "coral", size = 1) +
  geom_errorbar(aes(ymin=mean_n-ci, ymax=mean_n+ci), colour="coral", width=.1) 
```

```{r}
plot_n + 
  geom_line(data = teacher_n_by_school, aes(x = year, y = teacher_n, group = SchNum),alpha = .01, width = .25) +

  ylim(0,150) 
```

